### PR TITLE
Add branch protection rules

### PR DESCRIPTION
**Pull request by windsource**
Adds branch protection rules to the ank-sdk-rust and ank-sdk-python repositiories.

### CODE REVIEW

**Comment by netomi** [comment]
Not sure how you deal with release branches, but maybe you want to prevent that they are deleted or updated so you could adjust the rule for these branches to set `allow_deletions:true` and `lock_branch:true`.

Furthermore, there are now also rulesets that have the same functionality as branch protection rules, but have more features, see https://otterdog.readthedocs.io/en/latest/reference/organization/repository/ruleset/

An example of a ruleset to prevent tags from being modified at all can be found here:

https://github.com/eclipse-californium/.eclipsefdn/pull/1

**Comment by windsource** [comment]
@netomi Thanks for the hint. I will transfer the branch protection rules to rulesets. I think we do not want to allow deleting the protected branches but changes to those shall be allowed.
There are certain use cases that require us to move tags so we don't want to prohibit that.

**Comment by netomi** [comment]
hmmm, you will need to set `allows_creations: true` for the rulesets as you include a pattern for the release branches. You will probably create these branches on demand, but the ruleset as it is configured now, will prevent that.

**Comment by windsource** [comment]
@netomi thanks for fixing the format problems. I think the [playground](https://eclipse-ankaios.github.io/.eclipsefdn/playground/#__tabbed_1_9) is not using the format which is used in production.

**Comment by netomi** [comment]
it is indeed not up-to-date, will fix that, thanks for mentioning.

**Comment by netomi** [comment]
the reason is that the playground is only built when the repo got updated.

But we did change the model slightly to better group settings together, and this should trigger a rebuild for all the playgrounds as well. Did trigger it now manually, so it should be fixed in a minute.

The playground should actually be hosted at https://otterdog.eclipse.org so that it does not have to be generated for each organization.

**Comment by netomi** [comment]
its now updated:

image

you probably need to force refresh the page though.

**Review by inf17101 — APPROVED** [review]
LGTM 👍

**Comment by windsource** [comment]
@netomi Could you please review and approve the changes such that we can merge those?

**Review by netomi — APPROVED** [review]
LGTM, I added the setting `do_not_enforce_on_create: true` for the required status checks as your ruleset also targets release branches that needs to be created at one point in time. So with this settings the creation will not fail if some status checks are not present or successful.

I dont have much experience with this setting, but it should be safe to set it like that imho.

**Comment by netomi** [comment]
fyi: the playground is now moved to the dashboard, available at https://otterdog.eclipse.org/projects/automotive.ankaios/playground

There is also now a visualization of the default settings for convenience https://otterdog.eclipse.org/projects/automotive.ankaios/defaults

Let me know if something is missing in your opinion.

**Pull request merged**
