### PR TITLE
Create initial branch protection settings

### PR DESCRIPTION
**Pull request by inf17101**
Issue [#71](https://github.com/eclipse-ankaios/ankaios/issues/71)

**Note:**
The PR [#72](https://github.com/eclipse-ankaios/ankaios/pull/72) must be merged first, because it contains new job names as best practice. The job names are referenced here inside this PR for creating the list of required status checks.

### CODE REVIEW

**Review by netomi — APPROVED** [review]
LGTM

**Comment by inf17101** [comment]
> LGTM

I would like to ask two more questions:

- Who is merging this PR we or a reviewer of Eclipse that then automatically applies the changes with the otterdog cli?
- Why is in this PR the reviewer "eclipsefdn-security" missing?

Now, I am finalizing the other PR linked in the description above. If it is merged we can merge this PR here.

**Comment by netomi** [comment]
> I would like to ask two more questions:
> 
>     * Who is merging this PR we or a reviewer of Eclipse that then automatically applies the changes with the otterdog cli?

some EF IT staff merges the PR once its approved and applies the changes. In the near future we will have auto-approval e.g. if a project lead approves which then automatically merges and applies the changes.

>     * Why is in this PR the reviewer "eclipsefdn-security" missing?

I have already approved the PR, as I am member of the eclipsefdn-security team, GitHub might think no approval from this team is needed anymore and does not show the team anymore. That is consistent with all the other PRs that we have seen. Before a member of the team approves you will see the team.

> Now, I am finalizing the other PR linked in the description above. If it is merged we can merge this PR here.

ok

**Comment by inf17101** [comment]
I ask a Project lead if he can review this PR as well. Afterwards if the project lead approves we can merge this PR.
The other PR https://github.com/eclipse-ankaios/ankaios/pull/72 is merged now.

**Comment by netomi** [comment]
changes are live. btw I had to update config to enable discussions for the ankaios repo as it seems to have been enabled via the web ui.

**Pull request merged**
