### PR TITLE
Add branch protection rules on main branch

### PR DESCRIPTION
**Pull request by heurtematte**
related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3805

### CODE REVIEW

**Comment by netomi** [comment]
@inf17101 could you take a look at the suggested branch protection rule?

All settings that would be applied can be seen in the comment that has been added to this PR.
In case you want to have different settings (e.g. number of approvals), you can also take a look at the playground and adjust the settings as needed: https://eclipse-ankaios.github.io/.eclipsefdn/playground/

**Comment by inf17101** [comment]
@netomi, @heurtematte: Thank you so much for providing the initial config. Later, I will extend this PR with the config a little bit through additionally needed project settings. Afterwards it is ready for review. Thanks a lot.

**Comment by inf17101** [comment]
@netomi, @heurtematte: I have checked out the documentation and it says that otterdog must be executed manually to apply those settings. I am now able to run otterdog command line and I tried out this command: 'otterdog validate -c jsonnetfile.json' inside this repository, and it says validating but nothing more. For the first try I wanted to just do validating functionality :-D
I thought it is enough to create and merge this PR that the new config is applied. I have checked the GH Action Workflows of this repo and I could not find the "apply" command there. So for me it seems like, like the docu mentioned this must be executed manually. Could you support here how this process looks like in general?

In addition, I am not able to commit to this branch or do anything in this repository even if I committer at Eclipse-Ankaios. Could you give me the required permissions or must the Project Leads do that. I have changed the branch protection settings and wanted to commit but it does not work.

**Comment by netomi** [comment]
It is correct that atm the cli tool has to be run locally to apply the changes, however, this will be done by EF staff, so you just create PRs with suggested changes and once they are merged we apply these changes by running the tool on the latest version of the config.

In the near future this will be automated, which is already working but needs a bit more testing.

When you create a PR with changes, an automatic workflow will run to validate the changes and provide you feedback. Additionally you can use the playground to quickly test out changes:
https://eclipse-ankaios.github.io/.eclipsefdn/playground/

**Comment by netomi** [comment]
For creating PRs you should fork this repo and make changes there and then you can create a PR from your fork on this repo. That is how we have setup this for now, to have this repo as clean as possible.

**Comment by inf17101** [comment]
> For creating PRs you should fork this repo and make changes there and then you can create a PR from your fork on this repo. That is how we have setup this for now, to have this repo as clean as possible.

Thanks for the reply. Ok, I have made the config stricter, but this means we shall first merge this PR and then I will open a PR again for the adjusted settings?

One last question: In the docu there is mentioned in the list of required_status_checks we shall provide the workflow name. This means in our case we only need to put in "Build" and "PR Task List Check". So there is no need to select each individual job like you would usually do in the WebUI when setting required status checks?

**Comment by netomi** [comment]
Yeah you cant edit this PR that is a bit unfortunate but it served for demonstration purposes.
You can also just start from scratch and create your own PR from a fork and we close this one.

Regarding the status checks: I am not sure if I understand you correctly. The configuration of the rule should be the same as in the Web UI. You add all workflow names that you would like to pass.

Here is an example from another project:

https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet#L185

So you actually have to use the name of the job that produces the status rather than the name of the workflow.
Using the UI in this case would be more convenient, but once you get the knack it use quite efficient to just update the config.

**Comment by inf17101** [comment]
> Yeah you cant edit this PR that is a bit unfortunate but it served for demonstration purposes. You can also just start from scratch and create your own PR from a fork and we close this one.
> 
> Regarding the status checks: I am not sure if I understand you correctly. The configuration of the rule should be the same as in the Web UI. You add all workflow names that you would like to pass.
> 
> Here is an example from another project:
> 
> https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet#L185
> 
> So you actually have to use the name of the job that produces the status rather than the name of the workflow. Using the UI in this case would be more convenient, but once you get the knack it use quite efficient to just update the config.

Ok thank you for the providing the example repo. Then, according to this description https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idname and your link we must add all the job names instead of the workflow names. Thanks a lot.

Ok then let's close this PR and I will open a new one. By trying out by our-self it is good starting point to get familiar with the settings. I will put the same reviewer in my PR as it is in this PR.

**Comment by netomi** [comment]
Closing as superseded by https://github.com/eclipse-ankaios/.eclipsefdn/pull/2

**Pull request closed without merging**
