### PR TITLE
Add new required pipeline steps for optimized CI/CD

### PR DESCRIPTION
**Pull request by inf17101**
For the issue about optimizing CI/CD pipeline of the project https://github.com/eclipse-ankaios/ankaios/issues/91 I have changed the pipeline structure. Now, the required status checks must be adapted as well, which this PR does.

__This PR shall only be merged if the PR for optimizing CI/CD was approved. This is why it was opened as draft currently__ => https://github.com/eclipse-ankaios/ankaios/issues/91

### CODE REVIEW

**Review by krucod3 — APPROVED** [review]
LGTM 👍

**Comment by inf17101** [comment]
This PR can be merged now.

**Comment by netomi** [comment]
you can merge yourself by adding `/otterdog merge` as a comment.

**Pull request merged**
